### ISSUE TITLE
Possible player crash because of GSDK

### ISSUE THREAD

**Issue by sonicphi** [PlayFab/gsdk#112] opened 2021-12-23 23:16 UTC
I was testing my game's server when i was kicked from the server along with the other player, client logs dont show anything but server logs shows the following:

`LogPlayFabGSDK: Error: Failed to parse heartbeat
[2021.12.23-23.01.41:420][312]LogNet: Warning: UNetConnection::Tick: Connection TIMED OUT. Closing connection.. Elapsed: 60.00, Real: 60.00, Good: 60.00, DriverTime: 151.07, Threshold: 60.00, [UNetConnection] RemoteAddr: 85.241.65.128:60080, Name: IpConnection_2147482523, Driver: GameNetDriver IpNetDriver_2147482540, IsServer: YES, PC: GameplayPlayerControllerBP_C_2147482474, Owner: GameplayPlayerControllerBP_C_2147482474, UniqueId: Steam:076561198006820266
[2021.12.23-23.01.41:421][312]LogNet: Error: UEngine::BroadcastNetworkFailure: FailureType = ConnectionTimeout, ErrorString = UNetConnection::Tick: Connection TIMED OUT. Closing connection.. Elapsed: 60.00, Real: 60.00, Good: 60.00, DriverTime: 151.07, Threshold: 60.00, [UNetConnection] RemoteAddr: 85.241.65.128:60080, Name: IpConnection_2147482523, Driver: GameNetDriver IpNetDriver_2147482540, IsServer: YES, PC: GameplayPlayerControllerBP_C_2147482474, Owner: GameplayPlayerControllerBP_C_2147482474, UniqueId: Steam:076561198006820266, Driver = GameNetDriver IpNetDriver_2147482540
[2021.12.23-23.01.41:421][312]LogNet: NetworkFailure: ConnectionTimeout, Error: 'UNetConnection::Tick: Connection TIMED OUT. Closing connection.. Elapsed: 60.00, Real: 60.00, Good: 60.00, DriverTime: 151.07, Threshold: 60.00, [UNetConnection] RemoteAddr: 85.241.65.128:60080, Name: IpConnection_2147482523, Driver: GameNetDriver IpNetDriver_2147482540, IsServer: YES, PC: GameplayPlayerControllerBP_C_2147482474, Owner: GameplayPlayerControllerBP_C_2147482474, UniqueId: Steam:076561198006820266'
[2021.12.23-23.01.41:421][312]LogBlueprintUserMessages: [ProjectArenaGameInstanceBP_C_2147482601] NET ERROR: Connection timeout
[2021.12.23-23.01.41:421][312]LogNet: UNetConnection::Close: [UNetConnection] RemoteAddr: 85.241.65.128:60080, Name: IpConnection_2147482523, Driver: GameNetDriver IpNetDriver_2147482540, IsServer: YES, PC: GameplayPlayerControllerBP_C_2147482474, Owner: GameplayPlayerControllerBP_C_2147482474, UniqueId: Steam:076561198006820266, Channels: 11, Time: 2021.12.23-23.01.41
[2021.12.23-23.01.41:421][312]LogNet: UChannel::Close: Sending CloseBunch. ChIndex == 0. Name: [UChannel] ChIndex: 0, Closing: 0 [UNetConnection] RemoteAddr: 85.241.65.128:60080, Name: IpConnection_2147482523, Driver: GameNetDriver IpNetDriver_2147482540, IsServer: YES, PC: GameplayPlayerControllerBP_C_2147482474, Owner: GameplayPlayerControllerBP_C_2147482474, UniqueId: Steam:076561198006820266
[2021.12.23-23.01.41:453][313]LogTemp: Warning: LEAVING
[2021.12.23-23.01.41:453][313]LogTemp: Warning: PLAYERSTATE STUFF UPPER LEVEL
[2021.12.23-23.01.41:453][313]LogTemp: Warning: PLAYERSTATE STUFF LOWER LEVEL
[2021.12.23-23.01.41:454][313]LogTemp: Warning: team 1 lost all players
[2021.12.23-23.01.41:456][313]LogTemp: Warning: server shutdown time: 239.966797
[2021.12.23-23.01.41:484][314]LogTemp: Warning: empty server timer: 239.966797
[2021.12.23-23.01.41:484][314]LogTemp: Warning: server shutdown time: 239.933777
[2021.12.23-23.01.41:485][314]LogNet: Error: UEngine::BroadcastNetworkFailure: FailureType = ConnectionTimeout, ErrorString = UNetConnection::Tick: Connection TIMED OUT. Closing connection.. Elapsed: 60.00, Real: 60.00, Good: 60.00, DriverTime: 151.14, Threshold: 60.00, [UNetConnection] RemoteAddr: 85.241.65.222:53644, Name: IpConnection_2147482526, Driver: GameNetDriver IpNetDriver_2147482540, IsServer: YES, PC: GameplayPlayerControllerBP_C_2147482424, Owner: GameplayPlayerControllerBP_C_2147482424, UniqueId: Steam:076561198061035232, Driver = GameNetDriver IpNetDriver_2147482540
[2021.12.23-23.01.41:485][314]LogBlueprintUserMessages: [ProjectArenaGameInstanceBP_C_2147482601] NET ERROR: Connection timeout
[2021.12.23-23.01.41:485][314]LogNet: UNetConnection::Close: [UNetConnection] RemoteAddr: 85.241.65.222:53644, Name: IpConnection_2147482526, Driver: GameNetDriver IpNetDriver_2147482540, IsServer: YES, PC: GameplayPlayerControllerBP_C_2147482424, Owner: GameplayPlayerControllerBP_C_2147482424, UniqueId: Steam:076561198061035232, Channels: 11, Time: 2021.12.23-23.01.41
[2021.12.23-23.01.41:485][314]LogNet: UChannel::Close: Sending CloseBunch. ChIndex == 0. Name: [UChannel] ChIndex: 0, Closing: 0 [UNetConnection] RemoteAddr: 85.241.65.222:53644, Name: IpConnection_2147482526, Driver: GameNetDriver IpNetDriver_2147482540, IsServer: YES, PC: GameplayPlayerControllerBP_C_2147482424, Owner: GameplayPlayerControllerBP_C_2147482424, UniqueId: Steam:076561198061035232
[2021.12.23-23.01.41:519][315]LogTemp: Warning: LEAVING
[2021.12.23-23.01.41:520][315]LogTemp: Warning: PLAYERSTATE STUFF UPPER LEVEL
[2021.12.23-23.01.41:520][315]LogTemp: Warning: PLAYERSTATE STUFF LOWER LEVEL`

GSDK fails to parse a heart beat and then both players get kicked out, i am NOT sure that those are related but it is the first time i've seen this, never had this issue with the previous implementation as far as i can remember, it might be worth investigating.

**Comment by nassosterz-ms** [comment] 2022-01-02 16:03
Hello. I want to apologize for the late reply.

Could you provide some more information on your issue, as well as, if possible, steps to reproduce it.

**Specifically**:

- Is this on Windows or Linux?
- Is this on Process or Container mode?
- Does it occur when running the server with LocalMultiPlayerAgent or on PlayFab Multiplayer Servers (ThunderHead)?
- Are you using the UnrealPlugin or the UnityGSDK?
- Anything else specific to your issue that can help us replicate it / resolve it.

**Comment by sonicphi** [comment] 2022-01-02 17:34
Windows.
I am not sure what that means, it was running directly on the playfab backend.
This error occurred on on the playfab multiplayer servers, i have not been able to use use the localAgent since i switched to the plugin, the heartbeat parsing always fails.
UnrealPlugin.
Im running .26.
I am investigating other possible reasons for the timeouts but i have not tested anything yet because of the holidays, if i find anything worthwhile i will be sure to update here, some one mentioned in a thread that i not having the "sockets" dependency might cause timeouts, so thats what i am going to try next.

Even if this turns out to not be the plugins fault, the heartbeat parsing failure might be worth investigating.

**Comment by sonicphi** [comment] 2022-01-08 18:32
I have tested this locally as well on the local agent, same issue and it also fails to parse the heart beat every time, please let me know if you guys found anything i am a bit lost here.

**Comment by sonicphi** [comment] 2022-01-09 10:53
I did a bit more digging into this, i tried removing the plugin to see if i could connect but still not luck so im assuming the plugin is safe, right now i think its a issue with steam which i am trying to make work with playfab but having no luck.

**Comment by sonicphi** [comment] 2022-01-09 13:27
I think i figured it out.

I was using .24 before upgrading to use the plugin, in .24 my netdriver settings were defaulting to the IpNetDriver even tho i was using the steam net driver for some reason. After upgrading to .26 it stoped defaulting to the IpNetDriver and using the SteamNetDriver like it was suposed to and that was causing the issue, i had to change my engineconfig.ini settings to:

`[/Script/Engine.GameEngine]
!NetDriverDefinitions=ClearArray
NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="/Script/OnlineSubsystemUtils.IpNetDriver",DriverClassNameFallback="/Script/OnlineSubsystemUtils.IpNetDriver")
+NetDriverDefinitions=(DefName="DemoNetDriver",DriverClassName="/Script/Engine.DemoNetDriver",DriverClassNameFallback="/Script/Engine.DemoNetDriver")`

and then i can connect. 

I tested this locally, not in the backend yet but it should work.

**Comment by nassosterz-ms** [comment] 2022-01-10 18:39
Glad you worked out a solution. I didnt respond because I wasnt able to reproduce this issue. If you test it succesfully also on the playfab backend, do let us know!

**Comment by dgkanatsios** [comment] 2022-01-26 19:49
@sonicphi did you have a chance to try it out? If not we can close this issue. Thanks!

**Comment by sonicphi** [comment] 2022-01-27 08:04
Not yet unfortunately, work mixed with a bit of lazyness has prevented me from trying it in the playfasb servers, i will try to get to it this weekend.

**Comment by sonicphi** [comment] 2022-01-29 16:15
I have tested the connection in the playfab backend and its not getting timeout anymore so i think its safe to assume that the issue is not related to the plugin, im still getting a crash but i still have to investigate that. Go ahead and close this.

**Comment by sonicphi** [comment] 2022-01-29 18:12
I am absolutely stumped by this, the players connect fine but always get a timeout after 60 seconds, all of them, the game can be played normaly until the timeout happens.

**Comment by sonicphi** [comment] 2022-01-30 11:22
I am considering the option that i am doing something wrong with my implementation of the plugin. When working on the game instance do i need to do both the CPP implementation and the BP one? i am under the impression that you only need one of the options but at this point i will try anything...

**Comment by sonicphi** [comment] 2022-01-30 19:41
After further testing i managed to replicate the bug without the plugin so you can go ahead and close this, i still have no idea what is causing it tho....

**Comment by nassosterz-ms** [comment] 2022-01-31 18:39
You only need to implement one of cpp or blueprint. Thank you for testing the Plugin!

**Closed by nassosterz-ms** 2022-01-31 18:39 UTC
