### ISSUE TITLE
Issue with GSDK_CPP_Windows.lib (or libculr.dll not sure) on Unreal Engine 5.3 project compilation

### ISSUE THREAD

**Issue by D3valon** [PlayFab/gsdk#164] opened 2024-01-18 09:19 UTC
Hey all,
I encountered an issue where my previously healthy server build is now now "Pending for Heartbeat" and after like 10 min it status is Unhealthy.

I only updated my source engine of unreal from 5.2.1 to 5.3 and pulled an update for visual studio 2022 (17.8.5)

Tried different approaches, but it looks like the issue is with the libraries. This is just a guess though.
Compiling shows...
![image](https://github.com/PlayFab/gsdk/assets/62667856/4cc359ea-1683-4e70-9de5-33d526083a5e)

If I comment _PublicAdditionalLibraries.Add(GsdkLibs + "/libcurl.lib")_; out. It will compile, but with warnings.
![image](https://github.com/PlayFab/gsdk/assets/62667856/bb40fc53-3d87-429f-b271-eeb0117e0041)

I can package my server build also, but when trying to deploy it comes back as "Pending Heartbeat".

I am puzzled by this for days, can it be because of Visual Studio? I am just failing to see how an engine update can cause this.

Any advice would be much appreciated.

**Comment by tculotta** [comment] 2024-01-18 18:18
Thanks for bringing this up! We'll be looking into this.

**Comment by D3valon** [comment] 2024-01-18 21:03
Thanks for getting back to me,
 is there anything I could do in the time being? Or would you recommend any workaround? Should I try to update the engine to 5.3.2 perhaps?

Thanks!

**Comment by tculotta** [comment] 2024-01-19 00:02
Unfortunately this looks to simply be a breaking change introduced with 5.3. You can certainly try 5.3.2, but I don't necessarily expect that to work. Support for 5.3 is part of our backlog, and we'll be able to take a look at this then. In the meantime I would recommend moving back to 5.2.1 if you can.

**Comment by D3valon** [comment] 2024-01-23 13:55
Yes, I did check with 5.3.2 out of curiosity, but the problem is there. I will go back using 5.2.1 and will keep an eye out if there will be any update on this matter in the future. 

Just a side note, when I was browsing on the unreal discord, someone had similar issue with the libcurl.lib (libcurl.dll) LNK 2005, but apparently with 5.2.1. So I am a bit hesitant to put a pin on this, that it is caused by the engine, but after a week of investigation sadly nothing helped to bridge this problem.

**Comment by tculotta** [comment] 2024-01-23 18:00
If it can occur across versions, it could also be some conflict between multiple plugins of course, though I'm not sure what all attempts to pull in libcurl. That may require more investigation to tease out what could be conflicting there if that is the case.

**Comment by shawnryanbruno** [comment] 2024-02-02 16:05
> Yes, I did check with 5.3.2 out of curiosity, but the problem is there. I will go back using 5.2.1 and will keep an eye out if there will be any update on this matter in the future.
> 
> Just a side note, when I was browsing on the unreal discord, someone had similar issue with the libcurl.lib (libcurl.dll) LNK 2005, but apparently with 5.2.1. So I am a bit hesitant to put a pin on this, that it is caused by the engine, but after a week of investigation sadly nothing helped to bridge this problem.

Did 5.2.1 work out for you?  I can't get it to work in 5.3 either. :/

**Comment by shawnryanbruno** [comment] 2024-02-02 19:44
> Unfortunately this looks to simply be a breaking change introduced with 5.3. You can certainly try 5.3.2, but I don't necessarily expect that to work. Support for 5.3 is part of our backlog, and we'll be able to take a look at this then. In the meantime I would recommend moving back to 5.2.1 if you can.

At least AWS gamelift is keeping up with the latest UE releases. Any ETA on this updated release?

**Comment by D3valon** [comment] 2024-02-05 10:53
> 
> Did 5.2.1 work out for you? I can't get it to work in 5.3 either. :/

Hey, sorry about the late reply, yes I went back to 5.2.1 and that resolved it for now. I was investigating for over a week and tried the 5.3.2 build from Epic's branch, I had the same issue. Still not entirely sure what is causing it.

**Comment by tculotta** [comment] 2024-02-05 20:23
Confirming that we are indeed looking into this issue, though there's no answer to this just yet.

**Comment by shawnryanbruno** [comment] 2024-02-05 21:00
> Confirming that we are indeed looking into this issue, though there's no answer to this just yet.

I appreciate the hard work. Keep in mind - this is in fact breaking. If we have to wait too long, we may as well just move on to another backend.

**Comment by tculotta** [comment] 2024-02-06 20:46
I got the 5.3 version of the engine and was able to successfully build a project using the plugin there. After taking another look at the second image provided in the initial post, I'd like to verify the sdk version you're using in this scenario. The namespace in that image is Microsoft::Azure::Gaming which is defined in the cpp sdk but not the UnrealPlugin version.

Are you pulling the GSDK source from the [cpp folder](https://github.com/PlayFab/gsdk/tree/main/cpp/cppsdk) or the [UnrealPlugin folder](https://github.com/PlayFab/gsdk/tree/main/UnrealPlugin/Source/PlayFabGSDK) of this repo?

**Comment by D3valon** [comment] 2024-02-06 21:06
> I got the 5.3 version of the engine and was able to successfully build a project using the plugin there. After taking another look at the second image provided in the initial post, I'd like to verify the sdk version you're using in this scenario. The namespace in that image is Microsoft::Azure::Gaming which is defined in the cpp sdk but not the UnrealPlugin version.
> 
> Are you pulling the GSDK source from the [cpp folder](https://github.com/PlayFab/gsdk/tree/main/cpp/cppsdk) or the [UnrealPlugin folder](https://github.com/PlayFab/gsdk/tree/main/UnrealPlugin/Source/PlayFabGSDK) of this repo?

Okay thanks for checking it. I'm using the cpp folder, for it, which is unchanged since 5.1 and was working fine until now. Should I try the blueprint implementation then?

That gives me hope that you got it working. Is it deployed successfully on playfab as well?
Thanks!

**Comment by tculotta** [comment] 2024-02-06 21:12
You don't have to use the blueprint implementation to be clear. You can still use C++ with the Unreal plugin sdk [as shown here](https://github.com/PlayFab/gsdk/blob/main/UnrealPlugin/ThirdPersonMPGSDKSetup.md#c-implementation). The sdk from the cpp folder may have happened to work with some versions of Unreal, but that is not a supported scenario.

**Comment by shawnryanbruno** [comment] 2024-02-06 21:14
> You don't have to use the blueprint implementation to be clear. You can still use C++ with the Unreal plugin sdk [as shown here](https://github.com/PlayFab/gsdk/blob/main/UnrealPlugin/ThirdPersonMPGSDKSetup.md#c-implementation). The sdk from the cpp folder may have happened to work with some versions of Unreal, but that is not a supported scenario.

I am personally using only the UE Plugin. I don't use the CPP version. I'll take another look at it.

**Comment by shawnryanbruno** [comment] 2024-02-06 21:52
> You don't have to use the blueprint implementation to be clear. You can still use C++ with the Unreal plugin sdk [as shown here](https://github.com/PlayFab/gsdk/blob/main/UnrealPlugin/ThirdPersonMPGSDKSetup.md#c-implementation). The sdk from the cpp folder may have happened to work with some versions of Unreal, but that is not a supported scenario.

Also, the issue isn't building the project. The issue is when trying to run the server, it gives an error: Heartbeat endpoint and Server id are required configuration values.

**Comment by D3valon** [comment] 2024-02-06 22:06
I will look into it again tomorrow then, luckily I kept thr 5.3 engine as well just in case.

Just as shawnryanbruno said too, I was able to compile and package my project, but deployment to the pf server failed with constantly pending heartbeat. 

Did your project deployed all fine tculotta on pf as well?

**Comment by D3valon** [comment] 2024-02-07 10:02
Using the Unreal Plugin folder results in the same issue, except that during the compilation of the Server build i do not have the libcurl related errors to show up.
When I go onto deploying the build it is still pending on heartbeat.
Wondering if you managed to deploy. 
![image](https://github.com/PlayFab/gsdk/assets/62667856/d1985a72-2e6b-4711-9e4c-d4b0af8af2f9)

**Comment by shawnryanbruno** [comment] 2024-02-07 17:58
The entire community is so frustrated with GSDK right now, I can see alot of people leaving.

**Comment by shawnryanbruno** [comment] 2024-02-07 18:09
It just won't get past initialized. I give up.

**Comment by shawnryanbruno** [comment] 2024-02-07 20:52
This is absolutely ridiculous. This has completely shut down our project. We are losing so much money everyday because of this broken bug. FIX YOUR GARBAGE.

**Comment by tculotta** [comment] 2024-02-08 00:25
> Using the Unreal Plugin folder results in the same issue, except that during the compilation of the Server build i do not have the libcurl related errors to show up. When I go onto deploying the build it is still pending on heartbeat. Wondering if you managed to deploy. ![image](https://private-user-images.githubusercontent.com/62667856/302938109-d1985a72-2e6b-4711-9e4c-d4b0af8af2f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNDgwMDksIm5iZiI6MTcwNzM0NzcwOSwicGF0aCI6Ii82MjY2Nzg1Ni8zMDI5MzgxMDktZDE5ODVhNzItMmU2Yi00NzExLTllNGMtZDRiMGFmOGFmMmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDIzMTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0Y2Y2NWY3MDg0MzI5ODI2YmUxYmJkOGM2MzBjNmM4YzJlOTc1YWMzNjQ0Mzg5Y2E1NmJhOWNjZWIzYzJhNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aKeAEaY7wfNSG1111CkcyLsf0xozj__96FgcSKNoCGQ)

I'm glad that fixed the linker issues. I'll be closing this issue out since that is resolved. For this pending heartbeat behavior, that would be something PlayFab Support can help more with. If you can reproduce this issue with the LocalMultiplayerAgent, providing those logs would be helpful when you create that ticket. Otherwise if the server runs successfully with the local agent but fails when run on the PlayFab infrastructure, the logs from the actual VM should be helpful enough for their investigation.

**Closed by tculotta** 2024-02-08 00:24 UTC
